name: 'NRF Connect SDK CI action'
description: 'Building nrf connect sdk projects'
branding:
  color: blue
  icon: link
inputs:
  board:  # id of input
    description: 'Board for build'
    required: true
  build_dir:
    description: 'Building directory'
    required: true
    default: 'build'
  board_root:
    description: 'Root Directory where the boards can be found'
    required: true
  file_suffix:
    description: 'Configuration file suffix'
    required: true
    default: 'release'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bestsens/nrf-connect-sdk-ci:v2.7.0'
  args:
    - sh 
    - ./build.sh
    - .
    - ${{ inputs.board }}
    - ${{ inputs.build_dir }}
    - ${{ inputs.board_root }}
    - ${{ inputs.file_suffix }}
    