name: 'NRF Connect SDK CI action'
description: 'Building nrf connect sdk projects'
branding:
  color: blue
  icon: Link
inputs:
  board:  # id of input
    description: 'Board for build'
    required: true
  build_dir:
    description: 'Building directory'
    required: true
    default: 'build'
  mcuboot_conf_file:
    description: 'MCUboot configuration file'
    required: true
  conf_file:
    description: 'Configuration file'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/bestsens/nrf-connect-sdk-ci:v2.6.1'
  args:
    - west 
    - build
    - --build-dir 
    - ${{ inputs.build_dir }}
    - .
    - --pristine
    - --no-sysbuild
    - --board 
    - ${{ inputs.board }}
    - -Dmcuboot_CONF_FILE=${{ inputs.mcuboot_conf_file }}
    - -DCONF_FILE=${{ inputs.conf_file }}
