name: 'NRF Connect SDK CI action'
description: 'Building nrf connect sdk projects'
branding:
  color: blue
  icon: Link
inputs:
  board:  # id of input
    description: 'Board for build'
    required: true
  build_dir:
    description: 'Building directory'
    required: false
    default: 'build'
  add_flags:
    description: 'Additional flags'
    required: true
    default: '--no-sysbuild'
  mcuboot_conf_file:
    description: 'MCUboot configuration file'
  board_root:
    description: 'Root Directory where the boards can be found'
    required: false
    default: '.'
  file_suffix:
    description: 'Configuration file suffix'
    required: false
    default: 'release'
runs:
  using: 'docker'
  image: 'docker://sergeyladanov/nrf-connect-sdk:v3.0.2'
  args:
    - sh 
    - ./build.sh
    - .
    - --pristine
    - --board 
    - ${{ inputs.board }}
    - ${{ inputs.add_flags }}
    - -Dmcuboot_CONF_FILE=${{ inputs.mcuboot_conf_file }}
    - -DCONF_FILE=${{ inputs.conf_file }}
    - ${{ inputs.build_dir }}
    - ${{ inputs.board_root }}
    - ${{ inputs.file_suffix }}
    
