version: '2'

services:
  nrf:
    container_name: nrf
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NRF_CONNECT_TAG=v3.4.0
        - ZEPHYR_NEEDED_TAG=1.0.1
        - ZEPHYR_ARCHIVE_EXTENSION=xz
